openapi: 3.0.0
info:
  version: 1.0.0
  title: Common-Backend

paths:
  /api/v1/auth/sign-in:
    post:
      tags: [ Auth ]
      operationId: auth_sign_in
      summary: Вход пользователя в систему по логину и паролю
      responses:
        200:
          description: Успешный вход в систему

  /api/v1/auth/sign-up:
    post:
      tags: [ Auth ]
      operationId: auth_sign_up
      summary: Регистрация пользователя в системе
      responses:
        200:
          description: Успешная регистрация

  /api/v1/auth/refresh-token:
    post:
      tags: [ Auth ]
      operationId: auth_refresh_token
      summary: Обновление токена доступа к системе с помощью токена обновления
      responses:
        200:
          description: Успешное обновление токена доступа




  /api/v1/tests/my:
    get:
      tags: [ Tests ]
      operationId: tests_my
      summary: Получение "моих" созданных тестов
      responses:
        200:
          description: Список созданных тестов

  /api/v1/test/{testId}/get:
    get:
      tags: [ Tests ]
      operationId: test_by_id
      summary: Получение полной информации по конкретному тесту
      responses:
        200:
          description: Полная информация по тесту

  /api/v1/test/create:
    put:
      tags: [ Tests ]
      operationId: test_create
      summary: Создание нового теста
      responses:
        200:
          description: Полная информация по созданному тесту

  /api/v1/test/{testId}/delete:
    delete:
      tags: [ Tests ]
      operationId: test_delete
      summary: Удаление существующего теста
      responses:
        200:
          description: Успешное удаление теста




  /api/v1/test/{testId}/llm/launch:
    post:
      tags: [ LLM ]
      operationId: llm_launch
      summary: Запуск анализа теста с помощью генеративной языковой модели
      responses:
        200:
          description: Анализ теста успешно запущен

  /api/v1/test/{testId}/llm/status:
    get:
      tags: [ LLM ]
      operationId: llm_status
      summary: Получение текущего статуса анализа теста
      responses:
        200:
          description: Текущий статус анализа теста

  /api/v1/test/{testId}/llm/result:
    get:
      tags: [ LLM ]
      operationId: llm_result
      summary: Получение всех результатов анализа теста
      responses:
        200:
          description: Текущие результаты анализа теста

