apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: worker-drop-old-in-progress-llm-check-cron-job
  labels:
    app: worker-drop-old-ib-progress-llm-check
    repository: common-backend
    owner: Ferum-bot
    tier: backend
    infrastructure: golang
  namespace: default
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 120
      template:
        spec:
          nodeSelector:
            server-size: default
          containers:
            - name: worker-drop-old-in-progress-llm-check
              image: cr.yandex/crpqcg70aaep5tihmd33/common-backend-worker-drop-old-in-progress-llm-check:latest
              env:
                - name: ENVIRONMENT
                  value: "PRODUCTION"
                - name: MONGODB_URL
                  value: "{{MONGODB_URL}}"
                - name: MONGODB_DATABASE
                  value: "{{MONGODB_DATABASE}}"
          restartPolicy: Never