apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: worker-drop-old-in-progress-llm-check-cron-job
  labels:
    app: worker-drop-old-ib-progress-llm-check
    repository: common-backend
    owner: Ferum-bot
    tier: backend
    infrastructure: golang
  namespace: default
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 120
      template:
        spec:
          containers:
            - name: worker-drop-old-in-progress-llm-check
              image: $REPOSITORY_NAME:$IMAGE_TAG
          restartPolicy: Never