apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-llm-result-deployment
  labels:
    app: consumer-llm-result
    repository: common-backend
    owner: Ferum-bot
    tier: backend
    infrastructure: golang
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-llm-result
      tier: backend
      repository: common-backend
  template:
    metadata:
      labels:
        app: consumer-llm-result
        tier: backend
        owner: Ferum-bot
        repository: common-backend
        infrastructure: golang
    spec:
      nodeSelector:
        server-size: default
      containers:
        - name: consumer-llm-result-container
          image: cr.yandex/crpqcg70aaep5tihmd33/common-backend-consumer-llm-result:latest
          livenessProbe:
            httpGet:
              port: 8182
              path: /metrics
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8182
              path: /metrics
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              port: 8182
              path: /metrics
            failureThreshold: 30
            periodSeconds: 10
          ports:
            - containerPort: 8182
              hostPort: 8182
          env:
            - name: ENVIRONMENT
              value: "PRODUCTION"
            - name: SERVER_PORT
              value: "8182"
            - name: MONGODB_URL
              value: "{{MONGODB_URL}}"
            - name: MONGODB_DATABASE
              value: "{{MONGODB_DATABASE}}"
            - name: KAFKA_URL
              value: "{{KAFKA_URL}}"
            - name: KAFKA_TOPIC_LLM_RESULT
              value: "llm_tests_results"
            - name: KAFKA_CONSUMER_GROUP_ID
              value: "common_backend_consumer_llm_results"
