apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-backend-deployment
  labels:
    app: common-backend
    owner: Ferum-bot
    tier: backend
    infrastructure: golang
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: common-backend-application
      tier: backend
  template:
    metadata:
      labels:
        app: common-backend-application
        tier: backend
        owner: Ferum-bot
        infrastructure: golang
    spec:
      containers:
        - name: common-backend-container
          image: $REPOSITORY_NAME:$IMAGE_TAG
          livenessProbe:
            httpGet:
              port: 8181
              path: /metrics
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8181
              path: /metrics
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              port: 8181
              path: /metrics
            failureThreshold: 30
            periodSeconds: 10
          ports:
            - containerPort: 8181
              hostPort: 8181
