apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
    repository: common-backend
    owner: Ferum-bot
    tier: backend
    infrastructure: golang
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: server
      tier: backend
      repository: common-backend
  template:
    metadata:
      labels:
        app: server
        tier: backend
        owner: Ferum-bot
        repository: common-backend
        infrastructure: golang
    spec:
      containers:
        - name: server-container
          image: cr.yandex/crpqcg70aaep5tihmd33/common-backend-server:latest
          livenessProbe:
            httpGet:
              port: 8181
              path: /metrics
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8181
              path: /metrics
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              port: 8181
              path: /metrics
            failureThreshold: 30
            periodSeconds: 10
          ports:
            - containerPort: 8181
              hostPort: 8181
          env:
            - name: SERVER_PORT
              value: "8181"
            - name: ENVIRONMENT
              value: "PRODUCTION"
            - name: TOKEN_ACCESS_SIGN_SECRET
              value: "${{TOKEN_ACCESS_SIGN_SECRET}}"
            - name: TOKEN_REFRESH_SIGN_SECRET
              value: "${{TOKEN_REFRESH_SIGN_SECRET}}"
            - name: TOKEN_ISSUER
              value: "${{TOKEN_ISSUER}}"
            - name: TOKEN_ACCESS_LIFETIME_SECONDS
              value: "3600"
            - name: TOKEN_REFRESH_LIFETIME_SECONDS
              value: "2678400"
            - name: MONGODB_URL
              value: "${{MONGODB_URL}}"
            - name: MONGODB_DATABASE
              value: "${{MONGODB_DATABASE}}"
