apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-launch-llm-check-deployment
  labels:
    app: worker-launch-llm-check
    repository: common-backend
    owner: Ferum-bot
    tier: backend
    infrastructure: golang
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-launch-llm-check
      tier: backend
      repository: common-backend
  template:
    metadata:
      labels:
        app: worker-launch-llm-check
        tier: backend
        owner: Ferum-bot
        repository: common-backend
        infrastructure: golang
    spec:
      containers:
        - name: worker-launch-llm-check-container
          image: $REPOSITORY_NAME:$IMAGE_TAG
          livenessProbe:
            httpGet:
              port: 8183
              path: /metrics
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8183
              path: /metrics
            initialDelaySeconds: 10
            periodSeconds: 5
          startupProbe:
            httpGet:
              port: 8183
              path: /metrics
            failureThreshold: 30
            periodSeconds: 10
          ports:
            - containerPort: 8183
              hostPort: 8183
