name: Deploy API server

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Deploy Implementer'
        default: 'World'
        required: true

jobs:
  deploy:
   runs-on: ubuntu-latest
   environment: testing
   
   steps:
   - uses: actions/checkout@v3
   
   - name: Login to Yandex Cloud Container Registry
     id: login-cr
     uses: yc-actions/yc-cr-login@v1
     with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
         
   - name: Build docker image
     env:
       CR_REGISTRY: crpp4a802h6om9om40b4
       CR_REPOSITORY: mono-backend
       IMAGE_TAG: ${{ github.event.inputs.release-version }}
     run: docker build . --file Dockerfile --tag cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
     
   - name: Push docker image to Yandex.Cloud registry
     env:
       CR_REGISTRY: crpp4a802h6om9om40b4
       CR_REPOSITORY: mono-backend
       IMAGE_TAG: ${{ github.event.inputs.release-version }}
     run: docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
     
   - name: Wait untill Yandex.Cloud process new docker image
     uses: jakejarvis/wait-action@v0.1.1
     with:
       time: '30s'
          
   - name: Substitute the real value of variables
     env:
       ENV_MONGODB_URL: ${{ secrets.DATABASE_URL }}
       ENV_MONGODB_DATABASE: ${{ secrets.DATABASE_USER }}
       ENV_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
       ENV_TOKEN_SECRET: ${{ secrets.AUTH_TOKEN_SECRET }}
       ENV_TOKEN_AUDIENCE: ${{ secrets.AUTH_TOKEN_AUDIENCE }}
       ENV_TOKEN_ISSUER: ${{ secrets.AUTH_TOKEN_ISSUER }}
       KAFKA_URL: ${{ secrets.AUTH_TOKEN_ISSUER }}
     run: |
           sed -i 's|$REGISTRY_ID|crpp4a802h6om9om40b4|g' ./k8s/deployment.testing.yaml
           sed -i 's|$REPOSITORY_NAME|mono-backend|g' ./k8s/deployment.testing.yaml
           sed -i 's|$IMAGE_TAG|${{ github.event.inputs.release-version }}|g' ./k8s/deployment.testing.yaml
           sed -i "s|{{DATABASE_URL}}|$ENV_DATABASE_URL|g" ./k8s/deployment.testing.yaml
           sed -i "s|{{DATABASE_USER}}|$ENV_DATABASE_USER|g" ./k8s/deployment.testing.yaml
           sed -i "s|{{DATABASE_PASSWORD}}|$ENV_DATABASE_PASSWORD|g" ./k8s/deployment.testing.yaml
           sed -i "s|{{AUTH_TOKEN_SECRET}}|$ENV_TOKEN_SECRET|g" ./k8s/deployment.testing.yaml
           sed -i "s|{{AUTH_TOKEN_AUDIENCE}}|$ENV_TOKEN_AUDIENCE|g" ./k8s/deployment.testing.yaml
           sed -i "s|{{AUTH_TOKEN_ISSUER}}|$ENV_TOKEN_ISSUER|g" ./k8s/deployment.testing.yaml
  
   - name: Deploy to k8s
     uses: actions-hub/kubectl@v1.21.2
     env:
       KUBE_CONFIG: ${{ secrets.TESTING_K8S_CONFIG }}
     with:
       args: apply -f ./k8s/deployment.testing.yaml
